name: Sync GitHub Issues to Azure DevOps Work Items

permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened, labeled, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: MicrosoftEdge/action-issue-to-workitem@67b5ea438e4e45df824e94670af7db99bad80b4c
        env:
          ado_token: "${{ secrets.AZDO_PAT }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
        with:
          ado_organization: "${{ secrets.AZDO_ORGANIZATION }}"
          ado_project: "${{ secrets.AZDO_PROJECT }}"

          ado_work_item_type: "Task"
          ado_area_path: "${{ secrets.AZDO_AREA_PATH }}"

          ado_dont_check_if_exist: false
