# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.event.pull_request.number || github.ref) }}
  cancel-in-progress: true

jobs:
  approval:
    name: Approval
    environment: PR
    runs-on: ubuntu-24.04
    steps:
      - name: Approve
        run: echo "Workflow was approved"

  dependency_review:
    needs: [approval]
    name: Dependency Review
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          show-openssf-scorecard: false

  validate:
    name: Validate references
    needs: [approval]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: |
            reference-architectures/app/**/package-lock.json

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: "10.0.x"

      - name: Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ github.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Validate PR
        run: task validate

  success:
    needs: [validate, dependency_review]
    if: ${{ always() }}
    name: Pull Request Success
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: |
          if [[ "${{ needs.dependency_review.result }}" == "success" && "${{ needs.validate.result }}" == "success" ]]; then
            echo "All required checks passed."
          else
            echo "Some required checks did not pass."
            exit 1
          fi
