# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.event.pull_request.number || github.ref) }}
  cancel-in-progress: true

jobs:
  approval:
    name: Approval
    environment: PR
    runs-on: ubuntu-24.04
    steps:
      - name: Approve
        run: echo "Workflow was approved"

  dependency_review:
    needs: [approval]
    name: Dependency Review
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          show-openssf-scorecard: false

  validate:
    name: Validate references
    needs: [approval]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: |
            reference-architectures/app/**/package-lock.json

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: "10.0.x"

      - name: Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ github.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Validate PR
        run: task validate

  success:
    needs: [validate, dependency_review]
    if: ${{ always() }}
    name: Pull Request Success
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: |
          if [[ "${{ needs.dependency_review.result }}" == "success" && "${{ needs.validate.result }}" == "success" ]]; then
            echo "All required checks passed."
          else
            echo "Some required checks did not pass."
            exit 1
          fi
